version: '3.8'

services:
  # Tüm mevcut servisler (orjinal docker-compose.yml'den)
  # + PgAdmin ekliyoruz

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: iot-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgadmin-data:

